services:
  modaptovc-client:
    image: modaptovc.client:latest
    container_name: modaptovc-client
    restart: unless-stopped
    volumes:
      - ./modaptovc/data:/app/public/data
    ports:
      - 54321:8080
    depends_on:
      modaptovc-server:
        condition: service_started
    networks:
      - modapto
  modaptovc-server:
    image: modaptovc.server:latest
    container_name: modaptovc-server
    restart: unless-stopped
    volumes:
      - ./modaptovc/data:/app/data
    ports:
      - 12345:8080
    networks:
      - modapto
