services:
  modaptovc-client:
    image: modaptovc.client:latest
    container_name: modaptovc-client
    restart: unless-stopped
    volumes:
      - ./modaptovc/data:/app/public/data
    ports:
      - 80:80
    depends_on:
      modaptovc-server:
        condition: service_started
    networks:
      - modapto
  modaptovc-server:
    image: modaptovc.server:latest
    container_name: modaptovc-server
    restart: unless-stopped
    volumes:
      - ./modaptovc/data:/app/data
    ports:
      - 5259:5259
    networks:
      - modapto
